version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DD_AGENT_HOST=datadog
      - DD_TRACE_ENABLED=true
    depends_on:
      - datadog

  datadog:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=<SUA_API_KEY>
      - DD_SITE=datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
